# Generated by Django 5.2.17 on 2026-08-25 12:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0005_alter_campustoken_user_guesttokenrequest_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="campustoken",
            name="token_has_owner",
        ),
        migrations.AddConstraint(
            model_name="campustoken",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("guest_request__isnull", True), ("user__isnull", False)),
                    models.Q(("guest_request__isnull", False), ("user__isnull", True)),
                    _connector="OR",
                ),
                name="token_has_exactly_one_owner",
            ),
        ),
    ]
