# Generated by Django 5.2.17 on 2026-08-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0006_remove_campustoken_token_has_owner_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="guesttokenrequest",
            name="gender",
            field=models.CharField(
                choices=[
                    ("FEMALE", "Female"),
                    ("MALE", "Male"),
                    ("NON_BINARY", "Non-binary"),
                    ("PREFER_NOT_TO_SAY", "Prefer not to say"),
                ],
                default="PREFER_NOT_TO_SAY",
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="guesttokenrequest",
            name="live_photo",
            field=models.BinaryField(default=b""),
            preserve_default=False,
        ),
    ]
