# Generated by Django 5.2.17 on 2026-08-25 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0007_guesttokenrequest_gender_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guesttokenrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("MAIN_ADMIN_REQUIRED", "Main admin approval required"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
