# Generated by Django 5.1.15 on 2026-09-10 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_tokenscan_location"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="campustoken",
            name="token_has_exactly_one_owner",
        ),
    ]
