# Generated by Django 5.1.15 on 2026-09-12 07:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0007_location_tracking"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="locationhistory",
            index=models.Index(
                fields=["user", "-recorded_at"], name="dashboard_l_user_id_681bad_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="locationhistory",
            index=models.Index(
                fields=["recorded_at"], name="dashboard_l_recorde_b91c32_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userlocation",
            index=models.Index(
                fields=["recorded_at"], name="dashboard_u_recorde_f83c65_idx"
            ),
        ),
    ]
